"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const livro_1 = require("./livro");
const revista_1 = require("./revista");
const usuario_1 = require("./usuario");
const iblioteca_1 = require("./iblioteca");
const livro1 = new livro_1.Livro("O Senhor dos Anéis", 1954, "J.R.R. Tolkien", 1216);
const revista1 = new revista_1.Revista("National Geographic", 2024, "NG Media", 150);
const usuario1 = new usuario_1.Usuario("Maria Silva", 1);
const biblioteca = new iblioteca_1.Biblioteca();
biblioteca.adicionarItem(livro1);
biblioteca.adicionarItem(revista1);
biblioteca.registrarUsuario(usuario1);
usuario1.emprestarItem(livro1);
biblioteca.emprestarItem(usuario1, revista1);
