"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Livro_1 = require("./Livro");
const Biblioteca_1 = require("./Biblioteca");
const LivroDigital_1 = require("./LivroDigital");
let livro1 = new Livro_1.Livro("1984", "George Orwell", 16.09);
let livro2 = new Livro_1.Livro("O Senhor dos Anéis (box)", "Tolkien", 129.90);
let livro3 = new Livro_1.Livro("Admirável mundo novo", "Huxley", 34.70);
let livro4 = new Livro_1.Livro("O Pequeno Príncipe", "Saint-Exupery", 30);
let vetor = [livro1, livro2, livro3, livro4];
let biblio = new Biblioteca_1.Biblioteca(vetor);
biblio.listarLivros();
let livroDigital = new LivroDigital_1.LivroDigital("1984", "George Orwell", 9.90, "PDF");
biblio.adicionarLivro(livroDigital);
biblio.listarLivros();
