"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Produtos_1 = require("./Produtos");
const CarrinhoDeCompras_1 = require("./CarrinhoDeCompras");
const produto1 = new Produtos_1.Produto('Camisa', 50);
const produto2 = new Produtos_1.Produto('Calça', 100);
const produto3 = new Produtos_1.Produto('Sapato', 150);
const carrinho = new CarrinhoDeCompras_1.CarrinhoDeCompras();
carrinho.adicionarProduto(produto1);
carrinho.adicionarProduto(produto2);
carrinho.adicionarProduto(produto3);
const total = carrinho.calcularTotal();
console.log(`Total do carrinho: R$ ${total.toFixed(2)}`);
